"""Add the unused HumanEval problems to the corpus, verified by execution.

The corpus is dominated by one benchmark: mbpp supplies 555 of 1009 unique
targets, more than humaneval, BugsInPy and SWE-bench combined. That skew is not
cosmetic - SFT moves HumanEval +10.7 points and mbpp +3.3 - so a corpus that is
mostly mbpp is mostly the case where the method does not work.

The fix is to grow the scarce sources rather than delete verified mbpp targets,
because trimming reaches the ratio by making the corpus smaller and throws away
supervision that took execution to verify. 37 of the 164 HumanEval problems are
present in data/unified_dataset.json and used by no split, so they are pure
gain and need no network access.

What this does and does not do:

* It reuses the existing mutation operators rather than reimplementing them, so
  new records are generated by exactly the code that produced the current ones.
* Every mutant is verified by EXECUTION: the retained tests must pass on the
  reference and fail on the mutant. A mutant no test can distinguish is not a
  defect, it is a rewrite, and it is discarded.
* It writes to a versioned staging directory. The immutable V4.1 corpus is
  never modified; promoting this into a successor corpus is a separate,
  explicit step with its own hashes and manifest.
* Every new problem is TRAIN-only. These lineages appear in no split today, so
  adding them to train cannot leak into ablation_dev or val - and the script
  refuses any problem id that is already present anywhere, which is what makes
  that guarantee checkable rather than assumed.
"""
from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from harness.corpus import write_json
from harness.safe_execution import execute_code
from scripts.generate_mutations import (
    generate_mutations_for_function, is_clean_mutant, is_valid_python,
)
from utils.reproducibility import source_tree_sha256

VIEW = (
    ROOT / "data" / "corpus" / "v4_1_research_hardened_candidate" / "development_view"
)
UNIFIED = ROOT / "data" / "unified_dataset.json"
EXECUTION_TIMEOUT_SECONDS = 5.0
#: Cap per problem so one prolific function cannot re-create the skew being fixed.
MAX_MUTANTS_PER_PROBLEM = 12


def _problem_number(record_id: str) -> int | None:
    match = re.search(r"HumanEval[_/](\d+)", str(record_id), re.IGNORECASE)
    return int(match.group(1)) if match else None


def used_problem_ids() -> dict[int, str]:
    """Every HumanEval problem already present, and the split it lives in."""
    used: dict[int, str] = {}
    for split in ("train", "ablation_dev", "val"):
        path = VIEW / f"{split}.records.json"
        if not path.exists():
            continue
        for record in json.loads(path.read_text(encoding="utf-8")):
            number = _problem_number(record.get("id", ""))
            if number is not None:
                used.setdefault(number, split)
    return used


def runnable(test: str, entry_point: str) -> str:
    """Make a HumanEval test actually execute.

    HumanEval ships its tests as ``def check(candidate): ...`` with no call.
    Executed as-is the definition binds a name and asserts nothing, so it
    passes on the reference AND on the mutant, and every mutant looks
    undetectable. This is the third time in this project that a test defined
    but never invoked has silently reported success; the call is appended here
    rather than assumed.
    """
    body = str(test)
    if "def check(" in body and re.search(r"^\s*check\s*\(", body, re.MULTILINE) is None:
        return body.rstrip() + "\ncheck(" + entry_point + ")\n"
    return body


def verify(
    reference: str, mutant: str, tests: list[str], entry_point: str,
) -> dict[str, Any]:
    """A mutant counts only if a retained test passes clean and fails dirty."""
    passing = []
    killing = []
    for raw in tests:
        if not str(raw).strip():
            continue
        test = runnable(raw, entry_point)
        reference_ok, _, _ = execute_code(reference, test, EXECUTION_TIMEOUT_SECONDS)
        if not reference_ok:
            continue
        passing.append(test)
        mutant_ok, _, _ = execute_code(mutant, test, EXECUTION_TIMEOUT_SECONDS)
        if not mutant_ok:
            killing.append(test)
    return {
        "reference_valid_tests": len(passing),
        "killing_tests": len(killing),
        "verified": bool(killing),
    }


def build(limit_problems: int | None = None) -> dict[str, Any]:
    used = used_problem_ids()
    unified = json.loads(UNIFIED.read_text(encoding="utf-8"))
    problems = [row for row in unified if row.get("source") == "humaneval"]

    candidates = []
    for row in problems:
        number = _problem_number(row.get("id", ""))
        if number is None or number in used:
            continue
        candidates.append((number, row))
    candidates.sort()
    if limit_problems:
        candidates = candidates[:limit_problems]

    records: list[dict[str, Any]] = []
    rejected = collections.Counter()
    per_problem: dict[str, int] = {}

    for number, row in candidates:
        reference = str(row.get("code") or "")
        entry = str(row.get("entry_point") or "")
        tests = [str(t) for t in (row.get("test_cases") or []) if str(t).strip()]
        if not (reference and entry and tests):
            rejected["missing_reference_entry_or_tests"] += 1
            continue

        kept = 0
        for mutant, mutation_type, description in generate_mutations_for_function(
            reference
        ):
            if kept >= MAX_MUTANTS_PER_PROBLEM:
                break
            if not is_valid_python(mutant) or not is_clean_mutant(reference, mutant):
                rejected["invalid_or_identical_mutant"] += 1
                continue
            evidence = verify(reference, mutant, tests, entry)
            if not evidence["verified"]:
                # No retained test distinguishes it, so it is not a defect.
                rejected["no_test_distinguishes_the_mutant"] += 1
                continue
            kept += 1
            records.append({
                "id": f"mutation::humaneval_HumanEval_{number}_expand_{kept:03d}",
                "lineage": f"humaneval_HumanEval_{number}",
                "problem_number": number,
                "task_mode": "function",
                "source_dataset": "humaneval",
                "entry_point": entry,
                "reference_code": reference,
                "code_under_test": mutant,
                "mutation_type": mutation_type,
                "mutation_description": description,
                "tests": tests,
                "verification": evidence,
            })
        if kept:
            per_problem[f"HumanEval_{number}"] = kept
        else:
            rejected["problem_yielded_no_verified_mutant"] += 1

    lineages = {row["lineage"] for row in records}
    return {
        "schema_version": "oneiros_humaneval_expansion_v1",
        "source_tree_sha256": source_tree_sha256(ROOT),
        "sealed_final_test_accessed": False,
        "immutable_corpus_modified": False,
        "destination": "staging only; promotion into a successor corpus is separate",
        "split_assignment": "train",
        "leakage_guarantee": (
            "every problem here is absent from train, ablation_dev and val, "
            "checked against the corpus rather than assumed, so adding these "
            "lineages to train cannot leak into a held-out split"
        ),
        "problems_available_unused": len(candidates),
        "problems_with_verified_mutants": len(per_problem),
        "new_unique_lineages": len(lineages),
        "new_records": len(records),
        "mutants_per_problem": per_problem,
        "max_mutants_per_problem": MAX_MUTANTS_PER_PROBLEM,
        "rejected": dict(rejected),
        "verification_rule": (
            "a retained test must PASS on the reference and FAIL on the mutant; "
            "a mutant no test distinguishes is a rewrite, not a defect"
        ),
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit-problems", type=int, default=None,
                        help="verify the path on a few problems before the full run")
    parser.add_argument(
        "--output", type=Path,
        default=ROOT / "data" / "humaneval_expansion_staging" / "records.json",
    )
    arguments = parser.parse_args()

    report = build(arguments.limit_problems)
    write_json(arguments.output, report)
    summary = {k: v for k, v in report.items() if k not in {"records", "mutants_per_problem"}}
    print(json.dumps(summary, indent=2))
    print(f"\nwrote {report['new_records']} records to {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
