"""Add the unused HumanEval problems to the corpus, verified by execution.

The corpus is dominated by one benchmark: mbpp supplies 555 of 1009 unique
targets, more than humaneval, BugsInPy and SWE-bench combined. That skew is not
cosmetic - SFT moves HumanEval +10.7 points and mbpp +3.3 - so a corpus that is
mostly mbpp is mostly the case where the method does not work.

The fix is to grow the scarce sources rather than delete verified mbpp targets,
because trimming reaches the ratio by making the corpus smaller and throws away
supervision that took execution to verify. 37 of the 164 HumanEval problems are
present in data/unified_dataset.json and used by no split, so they are pure
gain and need no network access.

What this does and does not do:

* It reuses the existing mutation operators rather than reimplementing them, so
  new records are generated by exactly the code that produced the current ones.
* Every mutant is verified by EXECUTION: the retained tests must pass on the
  reference and fail on the mutant. A mutant no test can distinguish is not a
  defect, it is a rewrite, and it is discarded.
* It writes to a versioned staging directory. The immutable V4.1 corpus is
  never modified; promoting this into a successor corpus is a separate,
  explicit step with its own hashes and manifest.
* Every new problem is TRAIN-only. These lineages appear in no split today, so
  adding them to train cannot leak into ablation_dev or val - and the script
  refuses any problem id that is already present anywhere, which is what makes
  that guarantee checkable rather than assumed.
"""
from __future__ import annotations

import argparse
import ast
import collections
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from harness.corpus import write_json
from harness.safe_execution import execute_code
from scripts.generate_mutations import (
    generate_mutations_for_function, is_clean_mutant, is_valid_python,
)
from utils.reproducibility import source_tree_sha256

VIEW = (
    ROOT / "data" / "corpus" / "v4_1_research_hardened_candidate" / "development_view"
)
UNIFIED = ROOT / "data" / "unified_dataset.json"
EXECUTION_TIMEOUT_SECONDS = 5.0
#: Cap per problem so one prolific function cannot re-create the skew being fixed.
MAX_MUTANTS_PER_PROBLEM = 12


def _problem_number(record_id: str) -> int | None:
    match = re.search(r"HumanEval[_/](\d+)", str(record_id), re.IGNORECASE)
    return int(match.group(1)) if match else None


def used_problem_ids() -> dict[int, str]:
    """Every HumanEval problem already present, and the split it lives in."""
    used: dict[int, str] = {}
    for split in ("train", "ablation_dev", "val"):
        path = VIEW / f"{split}.records.json"
        if not path.exists():
            continue
        for record in json.loads(path.read_text(encoding="utf-8")):
            number = _problem_number(record.get("id", ""))
            if number is not None:
                used.setdefault(number, split)
    return used


def decompose_check(test: str, entry_point: str) -> list[str]:
    """Split HumanEval's check() into the corpus's individual assertions.

    Corpus records store one assert per test with its own execution-derived
    oracle label, not a single blob. Keeping the blob would produce records
    the rest of the pipeline cannot score the same way as every existing one,
    which is the train/eval shape mismatch this project has already paid for
    once. `candidate` is the parameter name HumanEval uses for the function
    under test, so it is rebound to the real entry point.
    """
    try:
        tree = ast.parse(str(test))
    except SyntaxError:
        return []
    out: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "check":
            for statement in node.body:
                if isinstance(statement, ast.Assert):
                    try:
                        rendered = ast.unparse(statement)
                    except Exception:
                        continue
                    out.append(
                        # Word-bounded: a bare substitution would also rewrite
                        # identifiers that merely contain the name.
                        re.sub(r"\bcandidate\b", entry_point, rendered)
                    )
    return out


def runnable(test: str, entry_point: str) -> str:
    """Make a HumanEval test actually execute.

    HumanEval ships its tests as ``def check(candidate): ...`` with no call.
    Executed as-is the definition binds a name and asserts nothing, so it
    passes on the reference AND on the mutant, and every mutant looks
    undetectable. This is the third time in this project that a test defined
    but never invoked has silently reported success; the call is appended here
    rather than assumed.
    """
    body = str(test)
    if "def check(" in body and re.search(r"^\s*check\s*\(", body, re.MULTILINE) is None:
        return body.rstrip() + "\ncheck(" + entry_point + ")\n"
    return body


def verify(
    reference: str, mutant: str, assertions: list[str],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Label each assertion by execution against the reference and the mutant.

    Two-sided, exactly as the corpus does it. An assertion that FAILS on the
    reference is dropped, not recorded: it would flag correct code as buggy and
    cannot certify anything. An assertion that passes both is kept but labelled
    non-distinguishing, because it is still a valid test of the function.
    """
    labelled: list[dict[str, Any]] = []
    reference_invalid = 0
    for code in assertions:
        if not code.strip():
            continue
        reference_ok, _, _ = execute_code(reference, code, EXECUTION_TIMEOUT_SECONDS)
        if not reference_ok:
            reference_invalid += 1
            continue
        mutant_ok, _, _ = execute_code(mutant, code, EXECUTION_TIMEOUT_SECONDS)
        labelled.append({"code": code, "kills": not mutant_ok})

    killing = sum(1 for a in labelled if a["kills"])
    return labelled, {
        "reference_valid_tests": len(labelled),
        "killing_tests": killing,
        "reference_invalid_excluded": reference_invalid,
        "verified": bool(killing),
    }


def _corpus_record(
    number: int, index: int, entry: str, reference: str, mutant: str,
    mutation_type: str, description: str, row: dict[str, Any],
    assertions: list[dict[str, Any]], evidence: dict[str, Any],
) -> dict[str, Any]:
    """Emit a record shaped exactly like the ones already in the corpus.

    Anything less makes these records second-class: the annotator, the
    multi-mutant builder and the evaluator all read these fields, and a record
    missing one is silently skipped rather than loudly rejected.
    """
    body = json.dumps(
        [reference, mutant, sorted(a["code"] for a in assertions)],
        sort_keys=True,
    )
    lineage = hashlib.sha256(
        f"humaneval::{entry}::{reference}".encode("utf-8")
    ).hexdigest()
    return {
        "schema_version": 1,
        "id": f"mutation::humaneval_HumanEval_{number}_expand_{index:05d}",
        "group_id": f"function:semantic:{lineage}",
        "language": "python",
        "task_mode": "function",
        "task_type": "hidden_mutation_reproduction",
        "test_format": "assert_statement",
        "entry_point": entry,
        "target_symbols": [entry],
        "specification": str(row.get("docstring") or ""),
        "support_context": "",
        "reference_code": reference,
        "code_under_test": mutant,
        "prompt_code_under_test": mutant,
        "content_hash": hashlib.sha256(body.encode("utf-8")).hexdigest(),
        "source": {"name": "oneiros_clean_mutations", "upstream": "humaneval"},
        "provenance": {
            "upstream_record_id": f"humaneval_HumanEval_{number}",
            "mutation_type": mutation_type,
            "mutation_description": description,
            "expansion": "humaneval_unused_problem_coverage_v1",
        },
        "quality": {
            "pair_behaviorally_verified": True,
            "oracle": "mutation_reference",
            "test_oracle_labels_execution_derived": True,
            "test_count": len(assertions),
            "killing_test_count": evidence["killing_tests"],
            "non_killing_test_count": len(assertions) - evidence["killing_tests"],
            "reference_invalid_tests_excluded": evidence["reference_invalid_excluded"],
            "candidate_policy_invalid_tests_excluded": 0,
            "current_execution_policy_reverified": True,
        },
        "field_lineage": {
            "prompt_code_under_test": "mutant_body_only",
            "specification": "humaneval_docstring",
            "support_context": "none",
            "target_symbols": "entry_point",
            "task_mode": "function",
            "test_format": "assert_statement",
        },
        "tests": [
            {
                "code": a["code"],
                "oracle": ("passes_reference_fails_target" if a["kills"]
                           else "passes_reference_passes_target"),
                "distinguishing": a["kills"],
                "reference_execution_status": "pass",
                "target_execution_status": ("assertion_error" if a["kills"]
                                            else "pass"),
            }
            for a in assertions
        ],
    }


def build(limit_problems: int | None = None) -> dict[str, Any]:
    used = used_problem_ids()
    unified = json.loads(UNIFIED.read_text(encoding="utf-8"))
    problems = [row for row in unified if row.get("source") == "humaneval"]

    candidates = []
    for row in problems:
        number = _problem_number(row.get("id", ""))
        if number is None or number in used:
            continue
        candidates.append((number, row))
    candidates.sort()
    if limit_problems:
        candidates = candidates[:limit_problems]

    records: list[dict[str, Any]] = []
    rejected = collections.Counter()
    per_problem: dict[str, int] = {}

    for number, row in candidates:
        reference = str(row.get("code") or "")
        entry = str(row.get("entry_point") or "")
        raw_tests = [str(t) for t in (row.get("test_cases") or []) if str(t).strip()]
        decomposed: list[str] = []
        for raw in raw_tests:
            decomposed.extend(decompose_check(raw, entry))
        if not (reference and entry and decomposed):
            rejected["missing_reference_entry_or_assertions"] += 1
            continue

        kept = 0
        for mutant, mutation_type, description in generate_mutations_for_function(
            reference
        ):
            if kept >= MAX_MUTANTS_PER_PROBLEM:
                break
            if not is_valid_python(mutant) or not is_clean_mutant(reference, mutant):
                rejected["invalid_or_identical_mutant"] += 1
                continue
            assertions, evidence = verify(reference, mutant, decomposed)
            if not evidence["verified"]:
                # No retained test distinguishes it, so it is not a defect.
                rejected["no_test_distinguishes_the_mutant"] += 1
                continue
            kept += 1
            records.append(_corpus_record(
                number, kept, entry, reference, mutant,
                mutation_type, description, row, assertions, evidence,
            ))
        if kept:
            per_problem[f"HumanEval_{number}"] = kept
        else:
            rejected["problem_yielded_no_verified_mutant"] += 1

    lineages = {row["group_id"] for row in records}
    return {
        "schema_version": "oneiros_humaneval_expansion_v1",
        "source_tree_sha256": source_tree_sha256(ROOT),
        "sealed_final_test_accessed": False,
        "immutable_corpus_modified": False,
        "destination": "staging only; promotion into a successor corpus is separate",
        "split_assignment": "train",
        "leakage_guarantee": (
            "every problem here is absent from train, ablation_dev and val, "
            "checked against the corpus rather than assumed, so adding these "
            "lineages to train cannot leak into a held-out split"
        ),
        "problems_available_unused": len(candidates),
        "problems_with_verified_mutants": len(per_problem),
        "new_unique_lineages": len(lineages),
        "new_records": len(records),
        "mutants_per_problem": per_problem,
        "max_mutants_per_problem": MAX_MUTANTS_PER_PROBLEM,
        "rejected": dict(rejected),
        "verification_rule": (
            "a retained test must PASS on the reference and FAIL on the mutant; "
            "a mutant no test distinguishes is a rewrite, not a defect"
        ),
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit-problems", type=int, default=None,
                        help="verify the path on a few problems before the full run")
    parser.add_argument(
        "--output", type=Path,
        default=ROOT / "data" / "humaneval_expansion_staging" / "records.json",
    )
    arguments = parser.parse_args()

    report = build(arguments.limit_problems)
    write_json(arguments.output, report)
    summary = {k: v for k, v in report.items() if k not in {"records", "mutants_per_problem"}}
    print(json.dumps(summary, indent=2))
    print(f"\nwrote {report['new_records']} records to {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
